website/contrib/code_block/urls.py
from django.urls import path

from .utils import PYGMENTS_VERSION_SLUG
from .views import pygments_styles

app_name = "code-block"

urlpatterns = [
    # HACK: Bake the pygments version into the URL, without needing a custom method
    path(
        f"pygments.{PYGMENTS_VERSION_SLUG}.css",
        pygments_styles,
        name="styles",
    )
]

website/urls.py
import re

from django.conf import settings
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_control, cache_page
from django.views.defaults import server_error
from django.views.generic import RedirectView
from django.views.static import serve
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.images.views.serve import ServeView
from wagtail_favicon.urls import urls as favicon_urls
from wagtailautocomplete.urls.admin import urlpatterns as autocomplete_admin_urls

from website.common.views import (
    AllPagesFeed,
    FaviconView,
    KeybaseView,
    RobotsView,
    page_not_found,
)

urlpatterns = [
    path("admin/autocomplete/", include(autocomplete_admin_urls)),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path(
        "code-block/",
        include("website.contrib.code_block.urls"),
    ),
    path(".well-known/", include("website.well_known.urls")),
    re_path(
        r"^images/([^/]*)/(\d*)/([^/]*)/[^/]*$",
        ServeView.as_view(action="redirect"),
        name="wagtailimages_serve",
    ),
    path("sitemap.xml", cache_page(60 * 60)(sitemap), name="sitemap"),
    path(
        "robots.txt",
        RobotsView.as_view(),
        name="robotstxt",
    ),
    path(
        "keybase.txt",
        KeybaseView.as_view(),
        name="keybase",
    ),
    path("feed/", AllPagesFeed(), name="feed"),
    path(".health/", include("health_check.urls")),
    path("", include("website.legacy.urls")),
    path("", include("website.search.urls")),
    path("api/", include("website.api.urls", namespace="api")),
    path(
        "@jake",
        RedirectView.as_view(url=f"https://{settings.ACTIVITYPUB_HOST}/@jake"),
    ),
    path("favicon.ico", FaviconView.as_view()),
    path("", include(favicon_urls)),
    re_path(
        r"^%s(?P<path>.*)$" % re.escape(settings.MEDIA_URL.lstrip("/")),
        cache_control(max_age=60 * 60)(serve),
        {"document_root": settings.MEDIA_ROOT},
    ),
]


if not settings.DEBUG:
    handler404 = "website.common.views.page_not_found"


if settings.DEBUG:
    # Add django-browser-reload
    urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))

    # Add django-debug-toolbar
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))


if settings.DEBUG or settings.TEST:
    urlpatterns.extend(
        [
            path("404/", page_not_found, name="404"),
            path("500/", server_error, name="500"),
        ]
    )

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

website/common/views.py
from datetime import datetime, time
from typing import Any, Optional

from django.contrib.syndication.views import Feed
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.templatetags.static import static
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_control, cache_page
from django.views.defaults import ERROR_404_TEMPLATE_NAME
from django.views.generic import RedirectView, TemplateView
from wagtail.models import Page
from wagtail.query import PageQuerySet
from wagtail_favicon.models import FaviconSettings
from wagtail_favicon.utils import get_rendition_url

from website.blog.models import BlogPostPage
from website.common.utils import get_site_title
from website.contrib.singleton_page.utils import SingletonPageCache
from website.home.models import HomePage
from website.search.models import SearchPage

from .feed_generators import CustomFeed
from .models import BaseListingPage, BasePage
from .utils import extend_query_params, get_ai_robots_txt


class Error404View(TemplateView):
    template_name = ERROR_404_TEMPLATE_NAME

    def render_to_response(self, context: dict, **response_kwargs: Any) -> HttpResponse:
        resolver_match = self.request.resolver_match
        if not resolver_match or resolver_match.url_name != "404":
            response_kwargs["status"] = 404
        return super().render_to_response(context, **response_kwargs)

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        context["homepage"] = HomePage.objects.get()
        context["search_url"] = SingletonPageCache.get_url(SearchPage, self.request)
        return context


page_not_found = Error404View.as_view()


@method_decorator(cache_control(max_age=60 * 60), name="dispatch")
class RobotsView(TemplateView):
    template_name = "robots.txt"
    content_type = "text/plain"

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        context["sitemap"] = self.request.build_absolute_uri(reverse("sitemap"))
        context["ai_robots_txt"] = get_ai_robots_txt()
        return context


@method_decorator(cache_control(max_age=60 * 60), name="dispatch")
class KeybaseView(TemplateView):
    template_name = "keybase.txt"
    content_type = "text/plain"


class AllPagesFeed(Feed):
    feed_type = CustomFeed
    link = "/"
    description_template = "feed-description.html"

    def __init__(self) -> None:
        self.style_tag = f'<?xml-stylesheet href="{static("contrib/pretty-feed-v3.xsl")}" type="text/xsl"?>'.encode()
        super().__init__()

    @method_decorator(cache_page(60 * 60))
    def __call__(
        self, request: HttpRequest, *args: list, **kwargs: dict
    ) -> HttpResponse:
        self.request = request
        response = super().__call__(request, *args, **kwargs)

        # Override Content-Type to allow styles
        response.headers["content-type"] = "application/xml"

        # Inject styles
        opening_xml = response.content.find(b"?>") + 2
        response.content = (
            response.content[:opening_xml]
            + b"\n"
            + self.style_tag
            + response.content[opening_xml:]
        )

        return response

    def feed_extra_kwargs(self, obj: None) -> dict:
        return {**super().feed_extra_kwargs(obj), "request": self.request}

    def title(self) -> str:
        return f"Feed :: {get_site_title()}"

    def items(self) -> PageQuerySet:
        return (
            Page.objects.live()
            .public()
            .exclude(depth__lte=2)
            .not_type(BaseListingPage)
            .specific()
            .order_by("-last_published_at")
        )

    def item_guid(self, item: BasePage) -> str:
        return item.get_full_url(request=self.request)

    def item_title(self, item: BasePage) -> str:
        return item.title

    def item_link(self, item: BasePage) -> str:
        return extend_query_params(
            item.get_full_url(request=self.request), {"utm_medium": "rss"}
        )

    def item_pubdate(self, item: BasePage) -> datetime:
        if item_date := getattr(item, "date", None):
            return datetime.combine(item_date, time())
        return item.first_published_at

    def item_updateddate(self, item: BasePage) -> datetime:
        return item.last_published_at

    def item_categories(self, item: BasePage) -> Optional[list[str]]:
        if isinstance(item, BlogPostPage):
            return item.tags_list.values_list("slug", flat=True)
        return None

    def item_enclosure_url(self, item: BasePage) -> Optional[str]:
        if not hasattr(item, "get_meta_image_url"):
            return ""

        image_url = item.get_meta_image_url(self.request)

        if image_url and image_url.startswith("/"):
            return self.request.build_absolute_uri(image_url)

        return image_url

    def item_enclosure_mime_type(self, item: BasePage) -> str:
        if not hasattr(item, "get_meta_image_mime"):
            return ""

        return item.get_meta_image_mime() or ""

    item_enclosure_length = 0


@method_decorator(cache_control(max_age=60 * 60), name="dispatch")
class FaviconView(RedirectView):
    def get_redirect_url(self) -> str:
        favicon_settings = FaviconSettings.for_request(self.request)
        size = FaviconSettings.icon_sizes[0]

        # Force image to PNG
        return get_rendition_url(
            favicon_settings.base_favicon_image, f"fill-{size}|format-png"
        )

website/common/templates/common/breadcrumbs.html
{% load wagtailcore_tags %}

{% if parents %}
  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      {% for parent in parents %}
        <li>
          <a href="{% pageurl parent %}">{{ parent.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </nav>
{% endif %}

website/common/templates/common/comments.html
<section class="container" id="comments">
  <comentario-comments></comentario-comments>
</section>

<script async defer src="https://comentario.theorangeone.net/comentario.js"></script>

website/common/templates/common/content-details.html
{% load wagtailcore_tags wagtail_cache %}

{% wagtailpagecache FRAGMENT_CACHE_TTL "content-details" %}
<div class="content-details field is-grouped">
  {% if page.date %}
    <span class="icon-text">
      <span class="icon">
        <i class="far fa-lg fa-calendar-alt"></i>
      </span>
      <span>{{ page.date|date:"Y-m-d" }}</span>
    </span>
  {% endif %}

  {% if page.show_reading_time %}
    <div class="icon-text" {% if page.word_count %}title="{{ page.word_count }} words"{% endif %}>
      <span class="icon">
        <i class="far fa-lg fa-clock"></i>
      </span>
      <span>{{ page.reading_time_display }}</span>
    </div>
  {% endif %}

  {% if page.tags_list %}
    <div class="icon-text is-family-code">
      <span class="icon">
        <a href="{{ page.tag_list_page_url }}" title="View all tags">
          <i class="fas fa-lg fa-tags"></i>
        </a>
      </span>
      {% for tag in page.tags_list %}
        <span><a title="{{ tag.name }}" href="{% pageurl tag %}">#{{ tag.slug }}</a></span>
      {% endfor %}
    </div>
  {% endif %}

  {% if page.slides_url %}
    <span class="icon-text">
      <a href="{{ page.slides_url }}">
        <span class="icon">
          <i class="fas fa-lg fa-images"></i>
        </span>
        <span>Slides</span>
      </a>
    </span>
  {% endif %}

  {% if page.video_url %}
    <span class="icon-text">
      <a href="{{ page.video_url }}">
        <span class="icon">
          <i class="fas fa-lg fa-film"></i>
        </span>
        <span>Video</span>
      </a>
    </span>
  {% endif %}

  {% if page.location_name and page.location_url %}
    <span class="icon-text">
      <a href="{{ page.location_url }}">
        <span class="icon">
          <i class="fas fa-lg fa-map-marker-alt"></i>
        </span>
        <span>{{ page.location_name }}</span>
      </a>
    </span>
  {% endif %}
</div>
{% endwagtailpagecache %}

website/common/templates/common/content_page.html
{% extends "wagtail_base.html" %}

{% load static sri navbar_tags %}

{% block content %}
  {% if page.body_html %}
    <section class="container content">
      {{ page.body_html|safe }}
    </section>
  {% endif %}
{% endblock %}

{% block post_toc %}
  <hr class="dropdown-divider" />
  <li>
    <a href="#comments">Comments</a>
  </li>
{% endblock %}

{% block post_content %}
  {% if not request.is_preview %}
    {% include "common/shareon.html" %}

    {% include "common/comments.html" %}

    {% if not request.user.is_authenticated %}
      {% support_pill %}
    {% endif %}
  {% endif %}
{% endblock %}

{% block extra_css %}
  {% sri_static "css/content-contrib.css" %}
  {% sri_static "contrib/shareon/shareon.min.css" %}

  <link rel="stylesheet" type="text/css" href="{% url 'code-block:styles' %}" />
{% endblock %}

{% block extra_js %}
  <script async defer type="text/javascript" src="{% static 'js/content.js' %}" integrity="{% sri_integrity_static 'js/content.js' %}"></script>
  <script async defer type="text/javascript" src="{% static 'contrib/shareon/shareon.iife.js' %}" integrity="{% sri_integrity_static 'contrib/shareon/shareon.iife.js' %}" init></script>
{% endblock %}

website/common/templates/common/footer.html
{% load wagtailcore_tags static %}

<footer class="footer">
  <div class="content has-text-centered">
    {% if online_accounts %}
      <p class="is-size-4 icon-text">
        {% for online_account in online_accounts %}<a class="icon" href="{{ online_account.url }}" title="{{ online_account.name }}"><i class="{{ online_account.icon }}"></i></a>{% endfor %}
      </p>
    {% endif %}
    <p class="is-size-6">
      &copy; <a href="{{ homepage_url }}">TheOrangeOne</a> {% now "Y" %}
    </p>
    <p id="to-top" class="is-size-7">
      <a class="scroll-top" role="button">To top</a>
      <a role="button" id="to-top-elevator" data-main-audio="{% static 'contrib/elevator-js/elevator.mp3' %}" data-end-audio="{% static 'contrib/elevator-js/ding.mp3' %}">
        <em>in style</em>
      </a>
    </p>
  </div>
</footer>

website/common/templates/common/listing-item.html
{% load wagtailcore_tags wagtail_cache util_tags %}

{% wagtailpagecache FRAGMENT_CACHE_TTL "listing-item" breadcrumbs show_listing_images %}
<article class="media listing-item">
  <div class="columns">
    <figure class="media-left column is-{{ show_listing_images|yesno:'3,1' }} image-column">
      {% if page.list_image_url %}
        <a href="{% pageurl page %}" class="image" title="{{ page.title }}">
          <img src="{{ page.list_image_url }}" alt="{{ page.hero_image_alt }}" loading="lazy" decoding="async" referrerpolicy="no-referrer" />
        </a>
      {% endif %}
    </figure>
    <div class="media-content column">
      <div>
        {% if breadcrumbs %}
          {% include "common/breadcrumbs.html" with parents=page.get_parent_pages %}
        {% endif %}
        <h2 class="title is-3">
          <a href="{% pageurl page %}">
            {{ page.title }}
            {% if page.is_external %}<i class="fa-solid fa-arrow-up-right-from-square" title="This page is from a external source"></i>{% endif %}
          </a>
        </h2>
        {% include "common/content-details.html" %}
        <p>{{ page.summary }}</p>
      </div>
    </div>
  </div>
</article>
{% endwagtailpagecache %}

website/common/templates/common/listing_page.html
{% extends "common/content_page.html" %}

{% load wagtailadmin_tags wagtailroutablepage_tags %}

{% block hero_buttons %}
  <a class="button is-radiusless" href="{% routablepageurl page 'random' %}" title="View random"><i class="fas fa-dice" aria-hidden="true"></i></a>

  {% if listing_pages.has_previous %}
    <a class="button is-radiusless" href="{% querystring page=listing_pages.previous_page_number %}" title="Previous page"><i class="fas fa-arrow-left" aria-hidden="true"></i></a>
  {% endif %}

  {% if listing_pages.has_next %}
    <a class="button is-radiusless" href="{% querystring page=listing_pages.next_page_number %}" title="Next page"><i class="fas fa-arrow-right" aria-hidden="true"></i></a>
  {% endif %}

  {{ block.super }}
{% endblock %}

{% block content_details %}
  {{ block.super }}

  {% if listing_pages.has_other_pages %}<p>Showing {{ listing_pages.start_index }}&mdash;{{ listing_pages.end_index }} of {{ listing_pages.paginator.count }}.</p>{% endif %}
{% endblock %}

{% block post_content %}
  <section class="container">
    {% for page in listing_pages %}
      {% block listing_item %}
        {% include "common/listing-item.html" %}
      {% endblock %}
    {% endfor %}
  </section>

  {% if listing_pages.has_other_pages %}
    <section class="container">
      <hr class="my-5" />
      {% include "common/pagination.html" with page=listing_pages %}
    </section>
  {% endif %}
{% endblock %}

website/common/templates/common/navbar.html
{% load wagtailcore_tags %}

<nav class="navbar is-family-code" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item home-link" href="{{ homepage_url }}">/home/theorangeone</a>

    <a role="button" class="navbar-burger" id="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-start">
      {% for nav_page in nav_pages %}
        <a class="navbar-item" href="{% pageurl nav_page %}">~/{{ nav_page.slug }}</a>
      {% endfor %}
    </div>

    <div class="navbar-end is-hidden-touch mr-2">
      {% if guestbook_page %}
        <a class="navbar-item navbar-icon" href="{% pageurl guestbook_page %}" title="{{ guestbook_page.title }}">
          <span class="icon">
            <i class="fas fa-book" aria-hidden="true"></i>
          </span>
        </a>
      {% endif %}
      <a class="navbar-item navbar-icon" href="{% url 'feed' %}" title="RSS">
        <span class="icon">
          <i class="fas fa-rss" aria-hidden="true"></i>
        </span>
      </a>
      {% if search_page_url %}
        <a class="navbar-item navbar-icon" href="{{ search_page_url }}" title="Search">
          <span class="icon">
            <i class="fas fa-search" aria-hidden="true"></i>
          </span>
        </a>
      {% endif %}
      <a class="navbar-item navbar-icon is-link" id="dark-mode-toggle" title="Toggle dark mode" role="button">
        <span class="icon">
          <i class="fa-solid fa-circle-half-stroke" aria-hidden="true"></i>
        </span>
      </a>
    </div>
  </div>
</nav>

website/common/templates/common/pagination.html
{% load wagtailadmin_tags %}

<nav class="pagination is-centered" role="navigation" title="pagination">
  {% if page.has_previous %}
    <a class="pagination-previous" title="Go to page {{ page.previous_page_number }}" href="{% querystring page=page.previous_page_number %}"><i class="fas fa-arrow-left" aria-hidden="true"></i></a>
  {% else %}
    <span class="pagination-previous is-disabled"><i class="fas fa-arrow-left" aria-hidden="true"></i></span>
  {% endif %}

  {% if page.has_next %}
    <a class="pagination-next" title="Go to page {{ page.next_page_number }}" href="{% querystring page=page.next_page_number %}"><i class="fas fa-arrow-right" aria-hidden="true"></i></a>
  {% else %}
    <span class="pagination-next is-disabled"><i class="fas fa-arrow-right" aria-hidden="true"></i></span>
  {% endif %}

  <ul class="pagination-list">
    {% if page.has_previous and page.previous_page_number != 1 %}
      <li>
        <a class="pagination-link" aria-label="Go to page 1" href="{% querystring page=1 %}">1</a>
      </li>
      <li>
        <span class="pagination-ellipsis">&hellip;</span>
      </li>
    {% endif %}

    {% if page.has_previous %}
      <li>
        <a class="pagination-link" title="Go to page {{ page.previous_page_number }}" href="{% querystring page=page.previous_page_number %}">{{ page.previous_page_number }}</a>
      </li>
    {% endif %}

    <li>
      <a class="pagination-link is-current" title="Page {{ page.number }}" aria-current="page" href="{% querystring page=page.number %}">{{ page.number }}</a>
    </li>

    {% if page.has_next %}
      <li>
        <a class="pagination-link" title="Go to page {{ page.next_page_number }}" href="{% querystring page=page.next_page_number %}">{{ page.next_page_number }}</a>
      </li>
    {% endif %}

    {% if page.has_next and page.next_page_number != page.paginator.num_pages %}
      <li>
        <span class="pagination-ellipsis">&hellip;</span>
      </li>
      <li>
        <a class="pagination-link" title="Go to page {{ page.paginator.num_pages }}" href="{% querystring page=page.paginator.num_pages %}">{{ page.paginator.num_pages }}</a>
      </li>
    {% endif %}
  </ul>
</nav>

website/common/templates/common/referrallink_snippet_link.html
<a href="{{ object.url }}">

website/common/templates/common/shareon.html
{% load wagtailcore_tags %}

<section class="container has-text-centered shareon-container" id="shareon">
  <p>Share this page</p>
  <div class="shareon" data-title="{{ page.title }}" data-url="{% fullpageurl page %}">
    <a class="facebook" title="Share on Facebook"></a>
    <a class="linkedin" title="Share on LinkedIn"></a>
    <a class="mastodon" title="Share on Mastodon"></a>
    <a class="pinterest" title="Share on Pintrest"></a>
    <a class="pocket" title="Share on Pocket"></a>
    <a class="reddit" title="Share on Reddit"></a>
    <a class="hackernews" title="Share on Hacker News"></a>
    <a class="fediverse" title="Share to the fediverse"></a>
    <a class="teams" title="Share on Teams"></a>
    <a class="telegram" title="Share on Telegram"></a>
    <a class="bluesky" title="Share on Bluesky"></a>
    <a class="twitter" title="Share on Twitter"></a>
    <a class="whatsapp" title="Share on WhatsApp"></a>
    <a class="email" title="Share by email"></a>
    <a role="button" class="copy-url" title="Copy URL"></a>
    <a role="button" class="web-share" title="Share"></a>
  </div>
</section>

website/common/templates/common/support-pill.html
{% load wagtailcore_tags %}

{% if support_page and page.id != support_page.id %}
  <a href="{% pageurl support_page %}" class="tag is-primary support-pill" title="If you like what I do, please consider supporting my work!">
    <i class="fas fa-praying-hands"></i>
  </a>
{% endif %}

website/common/templates/common/toc-item.html
<li>
  <a href="#{{ toc_item.slug }}">{{ toc_item.title }}</a>
  {% if toc_item.children %}
    <ul>
      {% for toc_item in toc_item.children %}
        {% include "common/toc-item.html" %}
      {% endfor %}
    </ul>
  {% endif %}
</li>